# Site settings
title: "Gabe Tiller"

# Build settings
markdown: kramdown
permalink: pretty

collections:
  projects:
    output: true

google_analytics: "UA-100153451-2"

baseurl: "" # the subpath of your site, e.g. /blog/
 url: "http://gabetiller.github.io" # the base hostname & protocol for your site
